# Site settings
title: KIT-10 Distract-O-Matic
email: stuart.feichtinger@gmail.com
description: Arduino-based laser turret/automatic cat toy

timezone: America/Chicago

# Build settings
highlighter: pygments
markdown:    kramdown

kramdown:
  input: GFM
